[package]
name = "soleil"
version = "0.1.0"
authors = ["Sheel Choksi"]
edition = "2018"

[dependencies]
cursive = { version = "0.16", features = ["toml"] }
serde = { version = "1.0", features = ["derive"] }
toml = { version = "0.5" }