shadow = false
borders = "simple"

[colors]
    view = "black"
    primary = "blue"
    secondary = "blue"
    tertiary = "yellow"
    background = ["black"]
    highlight = "green"
    highlight_inactive = "blue"
    title_primary = "blue"
    title_secondary = "blue"
